# Change these first
owner: lycaphe8x
repo: uptime

sites:
  - name: tienghoasaoviet
    url: https://www.tienghoasaoviet.com

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SaoViet_Monitor
  introTitle: "Hệ thống giám sát tình trạng hoạt động của hệ thống Tin Học Sao Việt (blogdaytinhoc.com)"
  introMessage: Hệ thống sẽ ghi nhận tình trạng giám sát website của Tin học Sao Việt. Đồng thời, cảnh báo về Email nếu website DownTime sau 5 phút
  navbar:
    - title: Tình trạng
      href: /uptime
    - title: Tin học Sao Việt
      href: https://www.blogdaytinhoc.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
